version: '3.3'
services:
  db:
    image: postgres:9-alpine
    restart: always
    volumes:
      - pg-data:/data/postgres
    environment:
      - POSTGRES_USER=platform
      - POSTGRES_PASSWORD=QdYx3D5y
  test: &test-base
    image: node:carbon
    command: bash -c "sh ./wait-for-db.sh && yarn test"
    working_dir: /usr/src/app
    depends_on:
      - db
    volumes:
      - .:/usr/src/app:Z
  watch_test:
    <<: *test-base
    command: ./node_modules/.bin/nodemon --exec yarn test
volumes:
  pg-data: