CREATE TABLE sys_user (
    id character varying NOT NULL,
    nick character varying,
    email character varying,
    name character varying,
    username character varying,
    activated smallint,
    level smallint,
    mysql_user_id integer,
    first_name character varying,
    last_name character varying,
    roles character varying[],
    active boolean,
    phone character varying,
    mailing_list smallint DEFAULT 0 NOT NULL,
    terms_conditions_accepted boolean,
    "when" timestamp with time zone,
    confirmed boolean,
    confirmcode character varying,
    salt character varying,
    pass character varying,
    admin boolean,
    modified timestamp with time zone,
    accounts character varying[],
    locale character varying,
    banned smallint,
    ban_reason character varying,
    init_user_type character varying,
    join_requests json[],
    last_login timestamp with time zone,
    lms_id character varying,
    CONSTRAINT pk_sys_user_id PRIMARY KEY (id)
);
CREATE UNIQUE INDEX sys_user_unique_email ON sys_user USING btree (email) WHERE ((email)::text <> ''::text);


CREATE TABLE cd_profiles (
    id character varying NOT NULL,
    name character varying,
    user_id character varying,
    alias character varying,
    dob timestamp with time zone,
    country json,
    city json,
    private boolean NOT NULL,
    gender character varying,
    last_edited timestamp without time zone DEFAULT now(),
    email character varying,
    phone character varying,
    parents text[],
    children text[],
    linkedin character varying,
    twitter character varying,
    languages_spoken text[],
    programming_languages text[],
    notes character varying,
    projects character varying,
    badges json[],
    place_geoname_id character varying,
    user_type character varying,
    optional_hidden_fields json,
    avatar json,
    required_fields_complete boolean DEFAULT false,
    ninja_invites json[],
    parent_invites json[],
    first_name character varying,
    last_name character varying,
    CONSTRAINT pk_cd_profiles_id PRIMARY KEY (id)
);

CREATE UNIQUE INDEX cd_profiles_unique_email ON cd_profiles USING btree (email) WHERE ((email)::text <> ''::text);
